//
//  CompanyList.swift
//  EquityStatus
//
//  Created by Paul Tangen on 11/30/19.
//  Copyright © 2019 Paul Tangen. All rights reserved.
//

import Foundation
import UIKit

struct CompanyList{
    
    // list of large cap and small cap companies found at: https://data.intrinio.com/companies on 30 Nov 2019
    // there are 16,000 companies, only the large cap and mid cap companies are of interest
    // there is no parameters in the api to query for companies in these categories
    
    // obtained the list by copying values from web site, pasting in Numbers file, adding cols for first, second and third seperators
    // export to csv, find and replace seperators and then adding rows to array below.
    
    // 1344 small cap companies are not included to keep things simple, not sure how valuable they are, could add them later

    let companyTickersAndNames: [String: String] = [
        "A" : "Agilent Technologies Inc",
        "AA" : "Alcoa Corp",
        "AABA" : "Altaba Inc",
        "AAL" : "American Airlines Group Inc",
        "AAN" : "Aaron's Inc",
        "AAON" : "AAON Inc",
        "AAP" : "Advance Auto Parts Inc",
        "AAPL" : "Apple Inc",
        "AAT" : "American Assets Trust Inc",
        "AAXN" : "Axon Enterprise Inc",
        "ABBV" : "AbbVie Inc",
        "ABC" : "AmerisourceBergen Corp",
        "ABCB" : "Ameris Bancorp",
        "ABG" : "Asbury Automotive Group Inc",
        "ABM" : "ABM Industries Inc",
        "ABMD" : "Abiomed Inc",
        "ABT" : "Abbott Laboratories",
        "ACAD" : "ACADIA Pharmaceuticals Inc",
        "ACC" : "American Campus Communities Inc",
        "ACGL" : "Arch Capital Group Ltd",
        "ACHC" : "Acadia Healthcare Company Inc",
        "ACIA" : "Acacia Communications Inc",
        "ACIW" : "ACI Worldwide Inc",
        "ACM" : "AECOM",
        "ACN" : "Accenture PLC",
        "ADBE" : "Adobe Inc.",
        "ADC" : "Agree Realty Corp",
        "ADI" : "Analog Devices Inc",
        "ADM" : "Archer Daniels Midland Co",
        "ADNT" : "Adient PLC",
        "ADP" : "Automatic Data Processing Inc",
        "ADS" : "Alliance Data Systems Corp",
        "ADSK" : "Autodesk Inc",
        "ADSW" : "Advanced Disposal Services Inc",
        "ADT" : "ADT Inc",
        "AEE" : "Ameren Corp",
        "AEIS" : "Advanced Energy Industries Inc",
        "AEL" : "American Equity Investment Life Holding Co",
        "AEO" : "American Eagle Outfitters Inc",
        "AEP" : "American Electric Power Company Inc",
        "AES" : "AES Corp",
        "AFG" : "American Financial Group Inc",
        "AFL" : "Aflac Inc",
        "AGCO" : "AGCO Corp",
        "AGIO" : "Agios Pharmaceuticals Inc",
        "AGN" : "Allergan plc",
        "AGNC" : "AGNC Investment Corp",
        "AGO" : "Assured Guaranty Ltd",
        "AGR" : "Avangrid Inc",
        "AHH" : "Armada Hoffler Properties Inc",
        "AHL" : "Aspen Insurance Holdings Ltd",
        "AIG" : "American International Group Inc",
        "AIMC" : "Altra Industrial Motion Corp",
        "AIN" : "Albany International Corp",
        "AIT" : "Applied Industrial Technologies Inc",
        "AIV" : "Apartment Investment and Management Co",
        "AIZ" : "Assurant Inc",
        "AJG" : "Arthur J Gallagher & Co",
        "AJRD" : "Aerojet Rocketdyne Holdings Inc",
        "AKAM" : "Akamai Technologies Inc",
        "AKR" : "Acadia Realty Trust",
        "AKTX" : "Akari Therapeutics PLC",
        "AL" : "Air Lease Corp",
        "ALB" : "Albemarle Corp",
        "ALE" : "ALLETE Inc",
        "ALGN" : "Align Technology Inc",
        "ALGT" : "Allegiant Travel Co",
        "ALK" : "Alaska Air Group Inc",
        "ALKS" : "Alkermes Plc",
        "ALL" : "Allstate Corp",
        "ALLE" : "Allegion PLC",
        "ALLY" : "Ally Financial Inc",
        "ALNY" : "Alnylam Pharmaceuticals Inc",
        "ALRM" : "Alarm.com Holdings Inc",
        "ALSN" : "Allison Transmission Holdings Inc",
        "ALTR" : "Altair Engineering Inc",
        "ALV" : "Autoliv Inc",
        "ALXN" : "Alexion Pharmaceuticals Inc",
        "AMAT" : "Applied Materials Inc",
        "AMCX" : "AMC Networks Inc",
        "AMD" : "Advanced Micro Devices Inc",
        "AME" : "Ametek Inc",
        "AMED" : "Amedisys Inc",
        "AMG" : "Affiliated Managers Group Inc",
        "AMGN" : "Amgen Inc",
        "AMH" : "American Homes 4 Rent",
        "AMKR" : "Amkor Technology Inc",
        "AMN" : "AMN Healthcare Services Inc",
        "AMP" : "Ameriprise Financial Inc",
        "AMT" : "American Tower Corp",
        "AMTD" : "TD Ameritrade Holding Corp",
        "AMZN" : "Amazon.com Inc",
        "AN" : "AutoNation Inc",
        "ANAT" : "American National Insurance Co",
        "ANET" : "Arista Networks Inc",
        "ANGI" : "ANGI Homeservices Inc.",
        "ANSS" : "ANSYS Inc",
        "ANTM" : "Anthem Inc",
        "AON" : "Aon PLC",
        "AOS" : "A. O. Smith Corp",
        "APA" : "Apache Corp",
        "APD" : "Air Products and Chemicals Inc",
        "APH" : "Amphenol Corp",
        "APO" : "Apollo Global Management LLC",
        "APPF" : "AppFolio Inc",
        "APPN" : "Appian Corp",
        "APTV" : "Aptiv PLC",
        "ARE" : "Alexandria Real Estate Equities Inc",
        "ARES" : "Ares Management Corp",
        "ARGO" : "Argo Group International Holdings Ltd",
        "ARI" : "Apollo Commercial Real Estate Finance Inc",
        "ARMK" : "Aramark",
        "ARNA" : "Arena Pharmaceuticals Inc",
        "ARNC" : "Arconic Inc",
        "ARW" : "Arrow Electronics Inc",
        "ARWR" : "Arrowhead Pharmaceuticals Inc",
        "ASB" : "Associated Banc-Corp",
        "ASGN" : "On Assignment Inc",
        "ASH" : "Ashland Global Holdings Inc",
        "ATI" : "Allegheny Technologies Inc",
        "ATKR" : "Atkore International Group Inc",
        "ATO" : "Atmos Energy Corp",
        "ATR" : "Aptargroup Inc",
        "ATUS" : "Altice USA Inc",
        "ATVI" : "Activision Blizzard Inc",
        "AVA" : "Avista Corp",
        "AVB" : "AvalonBay Communities Inc",
        "AVGO" : "Broadcom Inc",
        "AVLR" : "Avalara Inc",
        "AVP" : "Avon Products Inc",
        "AVT" : "Avnet Inc",
        "AVX" : "AVX Corp",
        "AVY" : "Avery Dennison Corp",
        "AWI" : "Armstrong World Industries Inc",
        "AWK" : "American Water Works Company Inc",
        "AWR" : "American States Water Co",
        "AXE" : "Anixter International Inc",
        "AXP" : "American Express Co",
        "AXS" : "AXIS Capital Holdings Ltd",
        "AXTA" : "Axalta Coating Systems Ltd",
        "AYI" : "Acuity Brands Inc",
        "AYR" : "Aircastle Ltd",
        "AYX" : "Alteryx Inc",
        "AZO" : "Autozone Inc",
        "AZPN" : "Aspen Technology Inc",
        "B" : "Barnes Group Inc",
        "BA" : "Boeing Co",
        "BAC" : "Bank of America Corp",
        "BAH" : "Booz Allen Hamilton Holding Corp",
        "BAX" : "Baxter International Inc",
        "BBT" : "BB&T Corp",
        "BBY" : "Best Buy Co Inc",
        "BC" : "Brunswick Corp",
        "BCO" : "Brinks Co",
        "BCPC" : "Balchem Corp",
        "BDC" : "Belden Inc",
        "BDN" : "Brandywine Realty Trust",
        "BDX" : "Becton Dickinson and Co",
        "BECN" : "Beacon Roofing Supply Inc",
        "BEN" : "Franklin Resources Inc",
        "BERY" : "Berry Global Group Inc",
        "BF.A" : "Brown-Forman Corp",
        "BFAM" : "Bright Horizons Family Solutions Inc",
        "BG" : "Bunge Ltd",
        "BGCP" : "BGC Partners Inc",
        "BGNE" : "BeiGene Ltd",
        "BHC" : "Bausch Health Companies Inc.",
        "BHF" : "Brighthouse Financial Inc",
        "BHVN" : "Biohaven Pharmaceutical Holding Company Ltd",
        "BIIB" : "Biogen Inc",
        "BIO" : "Bio Rad Laboratories Inc",
        "BJ" : "BJ's Wholesale Club Holdings Inc",
        "BK" : "Bank of New York Mellon Corp",
        "BKH" : "Black Hills Corp",
        "BKI" : "Black Knight, Inc.",
        "BKNG" : "Booking Holdings Inc",
        "BKU" : "BankUnited Inc",
        "BL" : "Blackline Inc",
        "BLD" : "TopBuild Corp",
        "BLDR" : "Builders FirstSource Inc",
        "BLK" : "BlackRock Inc",
        "BLKB" : "Blackbaud Inc",
        "BLL" : "Ball Corp",
        "BLMN" : "Bloomin' Brands Inc",
        "BLUE" : "bluebird bio Inc",
        "BMRN" : "Biomarin Pharmaceutical Inc",
        "BMY" : "Bristol-Myers Squibb Co",
        "BOH" : "Bank of Hawaii Corp",
        "BOKF" : "BOK Financial Corp",
        "BOX" : "Box Inc",
        "BPL" : "Buckeye Partners LP",
        "BPMC" : "Blueprint Medicines Corp",
        "BPOP" : "Popular Inc",
        "BR" : "Broadridge Financial Solutions Inc",
        "BRC" : "Brady Corp",
        "BRK.A" : "Berkshire Hathaway Inc",
        "BRKR" : "Bruker Corp",
        "BRKS" : "Brooks Automation Inc",
        "BRO" : "Brown & Brown Inc",
        "BRX" : "Brixmor Property Group Inc",
        "BSX" : "Boston Scientific Corp",
        "BURL" : "Burlington Stores Inc",
        "BWA" : "BorgWarner Inc",
        "BWXT" : "BWX Technologies Inc",
        "BXMT" : "Blackstone Mortgage Trust Inc",
        "BXP" : "Boston Properties Inc",
        "BXS" : "Bancorpsouth Bank",
        "BYD" : "Boyd Gaming Corp",
        "BYND" : "Beyond Meat Inc",
        "C" : "Citigroup Inc",
        "CABO" : "Cable ONE Inc",
        "CACC" : "Credit Acceptance Corp",
        "CACI" : "CACI International Inc",
        "CADE" : "Cadence Bancorp",
        "CAG" : "Conagra Brands Inc",
        "CAH" : "Cardinal Health Inc",
        "CALM" : "Cal-Maine Foods Inc",
        "CAR" : "Avis Budget Group Inc",
        "CARG" : "CarGurus Inc",
        "CASY" : "Caseys General Stores Inc",
        "CAT" : "Caterpillar Inc",
        "CATY" : "Cathay General Bancorp",
        "CB" : "Chubb Ltd",
        "CBM" : "Cambrex Corp",
        "CBOE" : "Cboe Global Markets Inc",
        "CBPO" : "China Biologic Products Holdings Inc",
        "CBRE" : "CBRE Group Inc",
        "CBRL" : "Cracker Barrel Old Country Store Inc",
        "CBS" : "CBS Corp",
        "CBSH" : "Commerce Bancshares Inc",
        "CBT" : "Cabot Corp",
        "CBU" : "Community Bank System Inc",
        "CC" : "Chemours Co",
        "CCI" : "Crown Castle International Corp",
        "CCK" : "Crown Holdings Inc",
        "CCL" : "Carnival Corp",
        "CCMP" : "Cabot Microelectronics Corp",
        "CCOI" : "Cogent Communications Holdings Inc",
        "CDAY" : "Ceridian HCM Holding Inc",
        "CDK" : "CDK Global Inc",
        "CDNS" : "Cadence Design Systems Inc",
        "CDW" : "CDW Corp",
        "CE" : "Celanese Corp",
        "CELG" : "Celgene Corp",
        "CEQP" : "Crestwood Equity Partners LP",
        "CERN" : "Cerner Corp",
        "CF" : "CF Industries Holdings Inc",
        "CFG" : "Citizens Financial Group Inc",
        "CFR" : "Cullen/Frost Bankers Inc",
        "CFX" : "Colfax Corp",
        "CG" : "Carlyle Group LP",
        "CGNX" : "Cognex Corp",
        "CHD" : "Church & Dwight Co Inc",
        "CHDN" : "Churchill Downs Inc",
        "CHE" : "Chemed Corp",
        "CHGG" : "Chegg Inc",
        "CHH" : "Choice Hotels International Inc",
        "CHRW" : "C.H. Robinson Worldwide Inc",
        "CHTR" : "Charter Communications Inc",
        "CIEN" : "Ciena Corp",
        "CIM" : "Chimera Investment Corp",
        "CINF" : "Cincinnati Financial Corp",
        "CIT" : "CIT Group Inc",
        "CL" : "Colgate-Palmolive Co",
        "CLDR" : "Cloudera Inc",
        "CLF" : "Cleveland-Cliffs Inc",
        "CLGX" : "Corelogic Inc",
        "CLH" : "Clean Harbors Inc",
        "CLI" : "Mack-Cali Realty Corp",
        "CLNY" : "Colony NorthStar Inc",
        "CLR" : "Continental Resources Inc",
        "CLX" : "Clorox Co",
        "CMA" : "Comerica Inc",
        "CMC" : "Commercial Metals Co",
        "CMCSA" : "Comcast Corp",
        "CMD" : "Cantel Medical Corp",
        "CME" : "CME Group Inc",
        "CMG" : "Chipotle Mexican Grill Inc",
        "CMI" : "Cummins Inc",
        "CMPR" : "Cimpress NV",
        "CMS" : "CMS Energy Corp",
        "CNA" : "CNA Financial Corp",
        "CNC" : "Centene Corp",
        "CNK" : "Cinemark Holdings Inc",
        "CNMD" : "Conmed Corp",
        "CNNE" : "Cannae Holdings Inc",
        "CNO" : "CNO Financial Group Inc",
        "CNP" : "CenterPoint Energy Inc",
        "CNS" : "Cohen & Steers Inc",
        "COF" : "Capital One Financial Corp",
        "COG" : "Cabot Oil & Gas Corp",
        "COHR" : "Coherent Inc",
        "COKE" : "Coca-Cola Bottling Co Consolidated",
        "COLB" : "Columbia Banking System Inc",
        "COLM" : "Columbia Sportswear Co",
        "COMM" : "CommScope Holding Company Inc",
        "CONE" : "CyrusOne Inc",
        "COO" : "Cooper Companies Inc",
        "COP" : "ConocoPhillips",
        "COR" : "CoreSite Realty Corp",
        "COST" : "Costco Wholesale Corp",
        "COTY" : "Coty Inc",
        "COUP" : "Coupa Software Inc",
        "CP" : "Canadian Pacific Railway Ltd",
        "CPB" : "Campbell Soup Co",
        "CPRI" : "Capri Holdings",
        "CPRT" : "Copart Inc",
        "CPT" : "Camden Property Trust",
        "CQP" : "Cheniere Energy Partners LP",
        "CR" : "Crane Co",
        "CREE" : "Cree Inc",
        "CRI" : "Carter's Inc",
        "CRL" : "Charles River Laboratories International Inc",
        "CRM" : "Salesforce.com Inc",
        "CROX" : "Crocs Inc",
        "CRS" : "Carpenter Technology Corp",
        "CRSP" : "CRISPR Therapeutics AG",
        "CRUS" : "Cirrus Logic Inc",
        "CRWD" : "Crowdstrike Holdings Inc",
        "CSCO" : "Cisco Systems Inc",
        "CSFL" : "Centerstate Bank Corp",
        "CSGP" : "CoStar Group Inc",
        "CSL" : "Carlisle Companies Inc",
        "CSOD" : "Cornerstone OnDemand Inc",
        "CSX" : "CSX Corp",
        "CTAS" : "Cintas Corp",
        "CTL" : "CenturyLink Inc",
        "CTLT" : "Catalent Inc",
        "CTSH" : "Cognizant Technology Solutions Corp",
        "CTXS" : "Citrix Systems Inc",
        "CUBE" : "CubeSmart",
        "CUZ" : "Cousins Properties Inc",
        "CVBF" : "CVB Financial Corp",
        "CVI" : "CVR Energy Inc",
        "CVLT" : "CommVault Systems Inc",
        "CVNA" : "Carvana Co",
        "CVS" : "CVS Health Corp",
        "CVX" : "Chevron Corp",
        "CW" : "Curtiss-Wright Corp",
        "CWEN.A" : "NRG Yield Inc",
        "CWK" : "Cushman & Wakefield PLC",
        "CWST" : "Casella Waste Systems Inc",
        "CWT" : "California Water Service Group",
        "CXO" : "Concho Resources Inc",
        "CXP" : "Columbia Property Trust Inc",
        "CY" : "Cypress Semiconductor Corp",
        "CZR" : "Caesars Entertainment Corp",
        "D" : "Dominion Energy Inc",
        "DAL" : "Delta Air Lines Inc",
        "DAN" : "Dana Inc",
        "DAR" : "Darling Ingredients Inc",
        "DBX" : "Dropbox Inc",
        "DCI" : "Donaldson Company Inc",
        "DCP" : "DCP Midstream LP",
        "DCPH" : "Deciphera Pharmaceuticals Inc",
        "DD" : "DuPont de Nemours, Inc.",
        "DE" : "Deere & Co",
        "DECK" : "Deckers Outdoor Corp",
        "DEI" : "Douglas Emmett Inc",
        "DELL" : "Dell Technologies Inc",
        "DFS" : "Discover Financial Services",
        "DG" : "Dollar General Corp",
        "DGX" : "Quest Diagnostics Inc",
        "DHI" : "D.R. Horton Inc",
        "DHR" : "Danaher Corp",
        "DIOD" : "Diodes Inc",
        "DIS" : "Walt Disney Co, The",
        "DISCA" : "Discovery Inc",
        "DISH" : "DISH Network Corp",
        "DK" : "Delek US Holdings Inc",
        "DKS" : "Dick's Sporting Goods Inc",
        "DLB" : "Dolby Laboratories Inc",
        "DLR" : "Digital Realty Trust Inc",
        "DLTR" : "Dollar Tree Inc",
        "DLX" : "Deluxe Corp",
        "DNKN" : "Dunkin' Brands Group Inc",
        "DOC" : "Physicians Realty Trust",
        "DOCU" : "Docusign Inc",
        "DORM" : "Dorman Products Inc",
        "DOV" : "Dover Corp",
        "DOW" : "Dow Inc.",
        "DPZ" : "Domino's Pizza Inc",
        "DRE" : "Duke Realty Corp",
        "DRH" : "DiamondRock Hospitality Co",
        "DRI" : "Darden Restaurants Inc",
        "DT" : "Dynatrace Holdings LLC",
        "DTE" : "DTE Energy Co",
        "DUK" : "Duke Energy Corp",
        "DVA" : "Davita Inc",
        "DVN" : "Devon Energy Corp",
        "DXC" : "DXC Technology Co",
        "DXCM" : "DexCom Inc",
        "EA" : "Electronic Arts Inc",
        "EAF" : "GrafTech International Ltd",
        "EBAY" : "eBay Inc",
        "EBS" : "Emergent BioSolutions Inc",
        "ECA" : "Encana Corp",
        "ECL" : "Ecolab Inc",
        "ED" : "Consolidated Edison Inc",
        "EE" : "El Paso Electric Co",
        "EEFT" : "Euronet Worldwide Inc",
        "EFX" : "Equifax Inc",
        "EGHT" : "8x8 Inc",
        "EGP" : "Eastgroup Properties Inc",
        "EHC" : "Encompass Health Corp",
        "EIDX" : "Eidos Therapeutics Inc",
        "EIX" : "Edison International",
        "EL" : "Estee Lauder Companies Inc",
        "ELAN" : "Elanco Animal Health Inc",
        "ELS" : "Equity LifeStyle Properties Inc",
        "ELY" : "Callaway Golf Co",
        "EME" : "EMCOR Group Inc",
        "EMN" : "Eastman Chemical Co",
        "EMR" : "Emerson Electric Co",
        "ENB" : "Enbridge Inc",
        "ENBL" : "Enable Midstream Partners LP",
        "ENLC" : "EnLink Midstream LLC",
        "ENPH" : "Enphase Energy Inc",
        "ENR" : "Energizer Holdings Inc",
        "ENS" : "EnerSys",
        "ENSG" : "Ensign Group Inc",
        "ENTG" : "Entegris Inc",
        "ENV" : "Envestnet Inc",
        "EOG" : "EOG Resources Inc",
        "EPAM" : "EPAM Systems Inc",
        "EPAY" : "Bottomline Technologies (DE) Inc",
        "EPD" : "Enterprise Products Partners LP",
        "EPR" : "EPR Properties",
        "EPRT" : "Essential Properties Realty Trust Inc",
        "EQC" : "Equity Commonwealth",
        "EQH" : "Axa Equitable Holdings Inc",
        "EQIX" : "Equinix Inc",
        "EQM" : "EQT Midstream Partners LP",
        "EQR" : "Equity Residential",
        "EQT" : "EQT Corp",
        "ERI" : "Eldorado Resorts Inc",
        "ES" : "Eversource Energy",
        "ESE" : "ESCO Technologies Inc",
        "ESGR" : "Enstar Group Ltd",
        "ESI" : "Element Solutions Inc",
        "ESNT" : "Essent Group Ltd",
        "ESRT" : "Empire State Realty Trust Inc",
        "ESS" : "Essex Property Trust Inc",
        "ET" : "Energy Transfer Equity LP",
        "ETFC" : "E*TRADE Financial Corp",
        "ETN" : "Eaton Corporation PLC",
        "ETR" : "Entergy Corp",
        "ETSY" : "Etsy Inc",
        "EV" : "Eaton Vance Corp",
        "EVBG" : "Everbridge Inc",
        "EVR" : "Evercore Inc",
        "EVRG" : "Evergy Inc",
        "EVTC" : "Evertec Inc",
        "EW" : "Edwards Lifesciences Corp",
        "EWBC" : "East West Bancorp Inc",
        "EXAS" : "Exact Sciences Corp",
        "EXC" : "Exelon Corp",
        "EXEL" : "Exelixis Inc",
        "EXLS" : "Exlservice Holdings Inc",
        "EXP" : "Eagle Materials Inc",
        "EXPD" : "Expeditors International of Washington Inc",
        "EXPE" : "Expedia Inc",
        "EXPO" : "Exponent Inc",
        "EXR" : "Extra Space Storage Inc",
        "EYE" : "National Vision Holdings Inc",
        "F" : "Ford Motor Co",
        "FAF" : "First American Financial Corp",
        "FANG" : "Diamondback Energy Inc",
        "FAST" : "Fastenal Co",
        "FB" : "Facebook Inc",
        "FBC" : "Flagstar Bancorp Inc",
        "FBHS" : "Fortune Brands Home & Security Inc",
        "FBP" : "First Bancorp",
        "FCFS" : "FirstCash Inc",
        "FCN" : "FTI Consulting Inc",
        "FCNCA" : "First Citizens BancShares Inc",
        "FCX" : "Freeport-McMoRan Inc",
        "FDS" : "FactSet Research Systems Inc",
        "FDX" : "FedEx Corp",
        "FE" : "FirstEnergy Corp",
        "FELE" : "Franklin Electric Co Inc",
        "FEYE" : "FireEye Inc",
        "FFBC" : "First Financial Bancorp",
        "FFIN" : "First Financial Bankshares Inc",
        "FFIV" : "F5 Networks Inc",
        "FGEN" : "FibroGen Inc",
        "FHB" : "First Hawaiian Inc",
        "FHN" : "First Horizon National Corp",
        "FIBK" : "First Interstate BancSystem Inc",
        "FICO" : "Fair Isaac Corp",
        "FII" : "Federated Investors Inc",
        "FIS" : "Fidelity National Information Services Inc",
        "FISV" : "Fiserv Inc",
        "FITB" : "Fifth Third Bancorp",
        "FIVE" : "Five Below Inc",
        "FIVN" : "Five9 Inc",
        "FIZZ" : "National Beverage Corp",
        "FL" : "Foot Locker Inc",
        "FLEX" : "Flex Ltd",
        "FLIR" : "FLIR Systems Inc",
        "FLO" : "Flowers Foods Inc",
        "FLOW" : "SPX FLOW Inc",
        "FLR" : "Fluor Corp",
        "FLS" : "Flowserve Corp",
        "FLT" : "Fleetcor Technologies Inc",
        "FMBI" : "First Midwest Bancorp Inc",
        "FMC" : "FMC Corp",
        "FN" : "Fabrinet",
        "FNB" : "F.N.B. Corp",
        "FND" : "Floor & Decor Holdings Inc",
        "FNF" : "Fidelity National Financial Inc",
        "FNMA" : "FEDERAL NATIONAL MORTGAGE ASSOCIATION FANNIE MAE",
        "FOLD" : "Amicus Therapeutics Inc",
        "FOXA" : "Fox Corp",
        "FOXF" : "Fox Factory Holding Corp",
        "FR" : "First Industrial Realty Trust Inc",
        "FRME" : "First Merchants Corp",
        "FRPT" : "Freshpet Inc",
        "FRT" : "Federal Realty Investment Trust",
        "FSLR" : "First Solar Inc",
        "FSS" : "Federal Signal Corp",
        "FTI" : "TechnipFMC PLC",
        "FTNT" : "Fortinet Inc",
        "FTV" : "Fortive Corp",
        "FUL" : "HB Fuller Co",
        "FULT" : "Fulton Financial Corp",
        "FUN" : "Cedar Fair LP",
        "G" : "Genpact Ltd",
        "GATX" : "GATX Corp",
        "GBCI" : "Glacier Bancorp Inc",
        "GBT" : "Global Blood Therapeutics Inc",
        "GD" : "General Dynamics Corp",
        "GDI" : "Gardner Denver Holdings Inc",
        "GE" : "General Electric Co",
        "GEL" : "Genesis Energy LP",
        "GGG" : "Graco Inc",
        "GH" : "Guardant Health, Inc.",
        "GHC" : "Graham Holdings Co",
        "GHDX" : "Genomic Health Inc",
        "GILD" : "Gilead Sciences Inc",
        "GIS" : "General Mills Inc",
        "GKOS" : "Glaukos Corp",
        "GLIBA" : "General Communication Inc",
        "GLPI" : "Gaming and Leisure Properties Inc",
        "GLW" : "Corning Inc",
        "GM" : "General Motors Co",
        "GMED" : "Globus Medical Inc",
        "GNRC" : "Generac Holdings Inc",
        "GNTX" : "Gentex Corp",
        "GNW" : "Genworth Financial Inc",
        "GOLF" : "Acushnet Holdings Corp",
        "GOOGL" : "Alphabet Inc",
        "GPC" : "Genuine Parts Co",
        "GPK" : "Graphic Packaging Holding Co",
        "GPN" : "Global Payments Inc",
        "GPS" : "Gap Inc",
        "GRA" : "W. R. Grace & Co",
        "GRMN" : "Garmin Ltd",
        "GRUB" : "GrubHub Inc",
        "GS" : "Goldman Sachs Group Inc",
        "GT" : "Goodyear Tire & Rubber Co",
        "GTES" : "Gates Industrial Corporation PLC",
        "GTLS" : "Chart Industries Inc",
        "GWPH" : "GW Pharmaceuticals PLC",
        "GWR" : "Genesee & Wyoming Inc",
        "GWRE" : "Guidewire Software Inc",
        "GWW" : "W W Grainger Inc",
        "H" : "Hyatt Hotels Corp",
        "HAE" : "Haemonetics Corp",
        "HAIN" : "Hain Celestial Group Inc",
        "HAL" : "Halliburton Co",
        "HALO" : "Halozyme Therapeutics Inc",
        "HAS" : "Hasbro Inc",
        "HBAN" : "Huntington Bancshares Inc",
        "HBI" : "HanesBrands Inc",
        "HCA" : "HCA Healthcare Inc",
        "HD" : "Home Depot Inc",
        "HDS" : "HD Supply Holdings Inc",
        "HE" : "Hawaiian Electric Industries Inc",
        "HEI" : "Heico Corp",
        "HELE" : "Helen of Troy Ltd",
        "HEP" : "Holly Energy Partners LP",
        "HES" : "Hess Corp",
        "HFC" : "HollyFrontier Corp",
        "HGV" : "Hilton Grand Vacations Inc",
        "HHC" : "Howard Hughes Corp",
        "HI" : "Hillenbrand Inc",
        "HIG" : "Hartford Financial Services Group Inc",
        "HII" : "Huntington Ingalls Industries Inc",
        "HIW" : "Highwoods Properties Inc",
        "HLF" : "Herbalife Ltd",
        "HLI" : "Houlihan Lokey Inc",
        "HLT" : "Hilton Worldwide Holdings Inc",
        "HMSY" : "HMS Holdings Corp",
        "HOG" : "Harley-Davidson Inc",
        "HOLX" : "Hologic Inc",
        "HOMB" : "Home BancShares Inc",
        "HON" : "Honeywell International Inc",
        "HP" : "Helmerich and Payne Inc",
        "HPE" : "Hewlett Packard Enterprise Co",
        "HPP" : "Hudson Pacific Properties Inc",
        "HPQ" : "HP Inc",
        "HQY" : "HealthEquity Inc",
        "HR" : "Healthcare Realty Trust Inc",
        "HRB" : "H & R Block Inc",
        "HRC" : "Hill-Rom Holdings Inc",
        "HRL" : "Hormel Foods Corp",
        "HRTX" : "Heron Therapeutics Inc",
        "HSIC" : "Henry Schein Inc",
        "HST" : "Host Hotels & Resorts Inc",
        "HSY" : "Hershey Co",
        "HTA" : "Healthcare Trust Of America Inc",
        "HTH" : "Hilltop Holdings Inc",
        "HTZ" : "Hertz Global Holdings Inc",
        "HUBB" : "Hubbell Inc",
        "HUBS" : "HubSpot Inc",
        "HUM" : "Humana Inc",
        "HUN" : "Huntsman Corp",
        "HWC" : "Hancock Holding Co",
        "HXL" : "Hexcel Corp",
        "HZNP" : "Horizon Pharma PLC",
        "IAC" : "IAC/InterActiveCorp",
        "IART" : "Integra LifeSciences Holdings Corp",
        "IBKC" : "IBERIABANK Corp",
        "IBKR" : "Interactive Brokers Group Inc",
        "IBM" : "International Business Machines Corp",
        "IBOC" : "International Bancshares Corp",
        "IBP" : "Installed Building Products Inc",
        "IBTX" : "Independent Bank Group Inc",
        "ICE" : "Intercontinental Exchange Inc",
        "ICPT" : "Intercept Pharmaceuticals Inc",
        "ICUI" : "ICU Medical Inc",
        "IDA" : "Idacorp Inc",
        "IDXX" : "IDEXX Laboratories Inc",
        "IEP" : "Icahn Enterprises LP",
        "IEX" : "IDEX Corp",
        "IFF" : "International Flavors & Fragrances Inc",
        "IGT" : "International Game Technology PLC",
        "ILMN" : "Illumina Inc",
        "IMMU" : "Immunomedics Inc",
        "IMO" : "Imperial Oil Ltd",
        "INCY" : "Incyte Corp",
        "INDB" : "Independent Bank Corp",
        "INFO" : "IHS Markit Ltd",
        "INGR" : "Ingredion Inc",
        "INOV" : "Inovalon Holdings Inc",
        "INSM" : "Insmed Inc",
        "INT" : "World Fuel Services Corp",
        "INTC" : "Intel Corp",
        "INTU" : "Intuit Inc",
        "INVH" : "Invitation Homes Inc",
        "IONS" : "Ionis Pharmaceuticals Inc",
        "IOSP" : "Innospec Inc",
        "IOVA" : "Iovance Biotherapeutics Inc",
        "IP" : "International Paper Co",
        "IPAR" : "Inter Parfums Inc",
        "IPG" : "Interpublic Group of Companies Inc",
        "IPGP" : "IPG Photonics Corp",
        "IPHI" : "Inphi Corp",
        "IR" : "Ingersoll-Rand PLC",
        "IRM" : "Iron Mountain Inc",
        "ISBC" : "Investors Bancorp Inc",
        "ISRG" : "Intuitive Surgical Inc",
        "IT" : "Gartner Inc",
        "ITGR" : "Integer Holdings Corp",
        "ITRI" : "Itron Inc",
        "ITT" : "ITT Inc",
        "ITW" : "Illinois Tool Works Inc",
        "IVR" : "Invesco Mortgage Capital Inc",
        "IVZ" : "Invesco Ltd",
        "JACK" : "Jack in the Box Inc",
        "JAZZ" : "Jazz Pharmaceuticals PLC",
        "JBGS" : "JBG SMITH Properties",
        "JBHT" : "J B Hunt Transport Services Inc",
        "JBL" : "Jabil Inc",
        "JBLU" : "JetBlue Airways Corp",
        "JBT" : "John Bean Technologies Corp",
        "JCI" : "Johnson Controls International PLC",
        "JCOM" : "J2 Global Inc",
        "JEC" : "Jacobs Engineering Group Inc",
        "JEF" : "Leucadia National Corp",
        "JELD" : "Jeld-Wen Holding Inc",
        "JHG" : "Janus Henderson Group PLC",
        "JJSF" : "J & J Snack Foods Corp",
        "JKHY" : "Jack Henry & Associates Inc",
        "JLL" : "Jones Lang LaSalle Inc",
        "JNJ" : "Johnson & Johnson",
        "JNPR" : "Juniper Networks Inc",
        "JPM" : "JPMorgan Chase & Co",
        "JW.A" : "John Wiley & Sons Inc",
        "JWN" : "Nordstrom Inc",
        "K" : "Kellogg Co",
        "KAR" : "KAR Auction Services Inc",
        "KBH" : "KB Home",
        "KBR" : "KBR Inc",
        "KDP" : "Keurig Dr Pepper Inc.",
        "KEX" : "Kirby Corp",
        "KEY" : "KeyCorp",
        "KEYS" : "Keysight Technologies Inc",
        "KFY" : "Korn/Ferry International",
        "KHC" : "Kraft Heinz Co",
        "KIM" : "Kimco Realty Corp",
        "KKR" : "KKR & Co LP",
        "KLAC" : "KLA-Tencor Corp",
        "KMB" : "Kimberly-Clark Corp",
        "KMI" : "Kinder Morgan Inc",
        "KMPR" : "Kemper Corp",
        "KMT" : "Kennametal Inc",
        "KMX" : "Carmax Inc",
        "KN" : "Knowles Corp",
        "KNSL" : "Kinsale Capital Group Inc",
        "KNX" : "Knight-Swift Transportation Holdings Inc",
        "KO" : "Coca-Cola Co",
        "KOS" : "Kosmos Energy Ltd",
        "KR" : "Kroger Co",
        "KRC" : "Kilroy Realty Corp",
        "KSS" : "Kohls Corp",
        "KSU" : "Kansas City Southern",
        "KTB" : "Kontoor Brands Inc",
        "KW" : "Kennedy-Wilson Holdings Inc",
        "L" : "Loews Corp",
        "LAD" : "Lithia Motors Inc",
        "LAMR" : "Lamar Advertising Co",
        "LANC" : "Lancaster Colony Corp",
        "LAUR" : "Laureate Education Inc",
        "LAZ" : "Lazard Ltd",
        "LB" : "L Brands Inc",
        "LBRDA" : "Liberty Broadband Corp",
        "LBTYA" : "Liberty Global PLC",
        "LCII" : "LCI Industries",
        "LDOS" : "Leidos Holdings Inc",
        "LEA" : "Lear Corp",
        "LECO" : "Lincoln Electric Holdings Inc",
        "LEG" : "Leggett & Platt Inc",
        "LFUS" : "Littelfuse Inc",
        "LGF.A" : "Lions Gate Entertainment Corp",
        "LGND" : "Ligand Pharmaceuticals Inc",
        "LH" : "Laboratory Corporation of America Holdings",
        "LHCG" : "LHC Group Inc",
        "LHX" : "L3Harris Technologies Inc",
        "LII" : "Lennox International Inc",
        "LILA" : "Liberty Latin America Ltd",
        "LITE" : "Lumentum Holdings Inc",
        "LIVN" : "LivaNova PLC",
        "LKQ" : "LKQ Corp",
        "LLY" : "Eli Lilly and Co",
        "LM" : "Legg Mason Inc",
        "LMT" : "Lockheed Martin Corp",
        "LNC" : "Lincoln National Corp",
        "LNG" : "Cheniere Energy Inc",
        "LNT" : "Alliant Energy Corp",
        "LOGI" : "Logitech International SA",
        "LOGM" : "LogMeIn Inc",
        "LOPE" : "Grand Canyon Education Inc",
        "LOW" : "Lowe's Companies Inc",
        "LPLA" : "LPL Financial Holdings Inc",
        "LPSN" : "LivePerson Inc",
        "LPT" : "Liberty Property Trust",
        "LPX" : "Louisiana-Pacific Corp",
        "LRCX" : "Lam Research Corp",
        "LSCC" : "Lattice Semiconductor Corp",
        "LSI" : "Life Storage Inc",
        "LSTR" : "Landstar System Inc",
        "LTXB" : "LegacyTexas Financial Group Inc",
        "LULU" : "Lululemon Athletica Inc",
        "LUV" : "Southwest Airlines Co",
        "LW" : "Lamb Weston Holdings Inc",
        "LXP" : "Lexington Realty Trust",
        "LYB" : "LyondellBasell Industries NV",
        "LYFT" : "LYFT Inc",
        "LYV" : "Live Nation Entertainment Inc",
        "M" : "Macy's Inc",
        "MA" : "MasterCard Inc",
        "MAA" : "Mid-America Apartment Communities Inc",
        "MAC" : "Macerich Co",
        "MAN" : "ManpowerGroup Inc",
        "MANH" : "Manhattan Associates Inc",
        "MANT" : "ManTech International Corp",
        "MAR" : "Marriott International Inc",
        "MAS" : "Masco Corp",
        "MASI" : "Masimo Corp",
        "MAT" : "Mattel Inc",
        "MCD" : "McDonald's Corp",
        "MCHP" : "Microchip Technology Inc",
        "MCK" : "McKesson Corp",
        "MCO" : "Moody's Corp",
        "MCY" : "Mercury General Corp",
        "MD" : "MEDNAX Inc",
        "MDB" : "Mongodb Inc",
        "MDC" : "MDC Holdings Inc",
        "MDCO" : "Medicines Co",
        "MDLZ" : "Mondelez International Inc",
        "MDRX" : "Allscripts Healthcare Solutions Inc",
        "MDT" : "Medtronic PLC",
        "MDU" : "MDU Resources Group Inc",
        "MEDP" : "Medpace Holdings Inc",
        "MELI" : "MercadoLibre Inc",
        "MET" : "Metlife Inc",
        "MFA" : "MFA Financial Inc",
        "MGEE" : "MGE Energy Inc",
        "MGM" : "MGM Resorts International",
        "MGP" : "MGM Growth Properties LLC",
        "MHK" : "Mohawk Industries Inc",
        "MIC" : "Macquarie Infrastructure Corp",
        "MIDD" : "Middleby Corp",
        "MIME" : "Mimecast Ltd",
        "MKC" : "McCormick & Company Inc",
        "MKL" : "Markel Corp",
        "MKSI" : "MKS Instruments Inc",
        "MKTX" : "Marketaxess Holdings Inc",
        "MLHR" : "Herman Miller Inc",
        "MLM" : "Martin Marietta Materials Inc",
        "MLNX" : "Mellanox Technologies Ltd",
        "MMC" : "Marsh & McLennan Companies Inc",
        "MMM" : "3M Co",
        "MMP" : "Magellan Midstream Partners LP",
        "MMS" : "Maximus Inc",
        "MNRO" : "Monro Inc",
        "MNST" : "Monster Beverage Corp",
        "MO" : "Altria Group Inc",
        "MOG.B" : "Moog Inc",
        "MOH" : "Molina Healthcare Inc",
        "MORN" : "Morningstar Inc",
        "MOS" : "Mosaic Co",
        "MPC" : "Marathon Petroleum Corp",
        "MPLX" : "MPLX LP",
        "MPW" : "Medical Properties Trust Inc",
        "MPWR" : "Monolithic Power Systems Inc",
        "MRCY" : "Mercury Systems Inc",
        "MRK" : "Merck & Co Inc",
        "MRNA" : "Moderna Inc",
        "MRO" : "Marathon Oil Corp",
        "MRTX" : "Mirati Therapeutics Inc",
        "MRVL" : "Marvell Technology Group Ltd",
        "MS" : "Morgan Stanley",
        "MSA" : "MSA Safety Inc",
        "MSCI" : "MSCI Inc",
        "MSFT" : "Microsoft Corp",
        "MSG" : "Madison Square Garden Co",
        "MSI" : "Motorola Solutions Inc",
        "MSM" : "MSC Industrial Direct Co Inc",
        "MTB" : "M&T Bank Corp",
        "MTCH" : "Match Group Inc",
        "MTD" : "Mettler-Toledo International Inc",
        "MTG" : "MGIC Investment Corp",
        "MTH" : "Meritage Homes Corp",
        "MTN" : "Vail Resorts Inc",
        "MTOR" : "Meritor Inc",
        "MTZ" : "MasTec Inc",
        "MU" : "Micron Technology Inc",
        "MUR" : "Murphy Oil Corp",
        "MUSA" : "Murphy USA Inc",
        "MXIM" : "Maxim Integrated Products Inc",
        "MYL" : "Mylan NV",
        "MYOK" : "MyoKardia Inc",
        "NATI" : "National Instruments Corp",
        "NAV" : "Navistar International Corp",
        "NAVI" : "Navient Corp",
        "NBIX" : "Neurocrine Biosciences Inc",
        "NBL" : "Noble Energy Inc",
        "NCLH" : "Norwegian Cruise Line Holdings Ltd",
        "NCR" : "NCR Corp",
        "NDAQ" : "Nasdaq Inc",
        "NDSN" : "Nordson Corp",
        "NEE" : "NextEra Energy Inc",
        "NEM" : "Newmont Mining Corp",
        "NEO" : "Neogenomics Inc",
        "NEOG" : "Neogen Corp",
        "NEP" : "Nextera Energy Partners LP",
        "NEU" : "NewMarket Corp",
        "NEWR" : "New Relic Inc",
        "NFG" : "National Fuel Gas Co",
        "NFLX" : "Netflix Inc",
        "NG" : "NovaGold Resources Inc",
        "NGHC" : "National General Holdings Corp",
        "NGVT" : "Ingevity Corp",
        "NHI" : "National Health Investors Inc",
        "NI" : "NiSource Inc",
        "NJR" : "New Jersey Resources Corp",
        "NKE" : "Nike Inc",
        "NKTR" : "Nektar Therapeutics",
        "NLOK" : "NortonLifeLock Inc.",
        "NLSN" : "Nielsen Holdings PLC",
        "NLY" : "Annaly Capital Management Inc",
        "NMIH" : "NMI Holdings Inc",
        "NMRK" : "Newmark Group Inc",
        "NNI" : "Nelnet Inc",
        "NNN" : "National Retail Properties Inc",
        "NOV" : "National Oilwell Varco Inc",
        "NOVT" : "Novanta Inc",
        "NOW" : "ServiceNow Inc",
        "NRG" : "NRG Energy Inc",
        "NRZ" : "New Residential Investment Corp",
        "NS" : "NuStar Energy LP",
        "NSA" : "National Storage Affiliates Trust",
        "NSIT" : "Insight Enterprises Inc",
        "NSP" : "Insperity Inc",
        "NTAP" : "NetApp Inc",
        "NTNX" : "Nutanix Inc",
        "NTRA" : "Natera Inc",
        "NTRS" : "Northern Trust Corp",
        "NUAN" : "Nuance Communications Inc",
        "NUE" : "Nucor Corp",
        "NUS" : "NU Skin Enterprises Inc",
        "NUVA" : "NuVasive Inc",
        "NVCR" : "Novocure Ltd",
        "NVDA" : "NVIDIA Corp",
        "NVR" : "NVR Inc",
        "NVRO" : "Nevro Corp",
        "NVT" : "nVent Electric PLC",
        "NVTA" : "Invitae Corp",
        "NWE" : "NorthWestern Corp",
        "NWL" : "Newell Brands Inc",
        "NWSA" : "News Corp",
        "NXST" : "Nexstar Media Group Inc",
        "NYCB" : "New York Community Bancorp Inc",
        "NYT" : "New York Times Co",
        "O" : "Realty Income Corp",
        "OAK" : "Oaktree Capital Group LLC",
        "OC" : "Owens Corning",
        "ODFL" : "Old Dominion Freight Line Inc",
        "OFC" : "Corporate Office Properties Trust",
        "OGE" : "OGE Energy Corp",
        "OGS" : "ONE Gas Inc",
        "OHI" : "Omega Healthcare Investors Inc",
        "OKE" : "ONEOK Inc",
        "OKTA" : "Okta Inc",
        "OLED" : "Universal Display Corp",
        "OLLI" : "Ollie's Bargain Outlet Holdings Inc",
        "OLN" : "Olin Corp",
        "OMC" : "Omnicom Group Inc",
        "OMCL" : "Omnicell Inc",
        "OMF" : "OneMain Holdings Inc",
        "ON" : "ON Semiconductor Corp",
        "ONB" : "Old National Bancorp",
        "ONCE" : "Spark Therapeutics Inc",
        "ORA" : "Ormat Technologies Inc",
        "ORCL" : "Oracle Corp",
        "ORI" : "Old Republic International Corp",
        "ORLY" : "O'Reilly Automotive Inc",
        "OSK" : "Oshkosh Corp",
        "OTEX" : "Open Text Corp",
        "OUT" : "OUTFRONT Media Inc",
        "OXY" : "Occidental Petroleum Corp",
        "OZK" : "Bank of the Ozarks",
        "PAA" : "Plains All American Pipeline LP",
        "PACW" : "PacWest Bancorp",
        "PAG" : "Penske Automotive Group Inc",
        "PAGP" : "Plains GP Holdings LP",
        "PANW" : "Palo Alto Networks Inc",
        "PAYC" : "Paycom Software Inc",
        "PAYX" : "Paychex Inc",
        "PB" : "Prosperity Bancshares Inc",
        "PBCT" : "People's United Financial Inc",
        "PBF" : "PBF Energy Inc",
        "PCAR" : "PACCAR Inc",
        "PCG" : "PG&E Corp",
        "PCH" : "PotlatchDeltic Corp",
        "PCTY" : "Paylocity Holding Corp",
        "PDM" : "Piedmont Office Realty Trust Inc",
        "PE" : "Parsley Energy Inc",
        "PEB" : "Pebblebrook Hotel Trust",
        "PEG" : "Public Service Enterprise Group Inc",
        "PEGA" : "Pegasystems Inc",
        "PEGI" : "Pattern Energy Group Inc",
        "PEN" : "Penumbra Inc",
        "PENN" : "Penn National Gaming Inc",
        "PEP" : "PepsiCo Inc",
        "PFE" : "Pfizer Inc",
        "PFG" : "Principal Financial Group Inc",
        "PFPT" : "Proofpoint Inc",
        "PFSI" : "PennyMac Financial Services Inc",
        "PG" : "Procter & Gamble Co",
        "PGR" : "Progressive Corp",
        "PGRE" : "Paramount Group Inc",
        "PH" : "Parker-Hannifin Corp",
        "PHM" : "PulteGroup Inc",
        "PII" : "Polaris Industries Inc",
        "PINC" : "Premier Inc",
        "PINS" : "Pinterest Inc",
        "PK" : "Park Hotels & Resorts Inc",
        "PKG" : "Packaging Corp of America",
        "PKI" : "PerkinElmer Inc",
        "PLAN" : "Anaplan Inc",
        "PLD" : "Prologis Inc",
        "PLNT" : "Planet Fitness Inc",
        "PLXS" : "Plexus Corp",
        "PM" : "Philip Morris International Inc",
        "PMT" : "PennyMac Mortgage Investment Trust",
        "PNC" : "PNC Financial Services Group Inc",
        "PNFP" : "Pinnacle Financial Partners Inc",
        "PNM" : "PNM Resources Inc",
        "PNR" : "Pentair plc",
        "PNW" : "Pinnacle West Capital Corp",
        "PODD" : "Insulet Corp",
        "POL" : "PolyOne Corp",
        "POOL" : "Pool Corp",
        "POR" : "Portland General Electric Co",
        "POST" : "Post Holdings Inc",
        "POWI" : "Power Integrations Inc",
        "PPC" : "Pilgrims Pride Corp",
        "PPG" : "PPG Industries Inc",
        "PPL" : "PPL Corp",
        "PQG" : "PQ Group Holdings Inc",
        "PRA" : "ProAssurance Corp",
        "PRAH" : "PRA Health Sciences Inc",
        "PRGO" : "Perrigo Company PLC",
        "PRI" : "Primerica Inc",
        "PRLB" : "Proto Labs Inc",
        "PRLE" : "Pillarstone Capital REIT",
        "PRO" : "PROS Holdings Inc",
        "PRU" : "Prudential Financial Inc",
        "PSA" : "Public Storage",
        "PSB" : "PS Business Parks Inc",
        "PSMT" : "PriceSmart Inc",
        "PSTG" : "Pure Storage Inc",
        "PSX" : "Phillips 66",
        "PSXP" : "Phillips 66 Partners LP",
        "PTC" : "PTC Inc",
        "PTLA" : "Portola Pharmaceuticals Inc",
        "PVH" : "PVH Corp",
        "PVTL" : "Pivotal Software Inc",
        "PWR" : "Quanta Services Inc",
        "PXD" : "Pioneer Natural Resources Co",
        "PYPL" : "PayPal Holdings Inc",
        "QCOM" : "Qualcomm Inc",
        "QDEL" : "Quidel Corp",
        "QLYS" : "Qualys Inc",
        "QSR" : "Restaurant Brands International Inc",
        "QTWO" : "Q2 Holdings Inc",
        "QURE" : "Uniqure NV",
        "R" : "Ryder System Inc",
        "RAMP" : "Acxiom Corp",
        "RARE" : "Ultragenyx Pharmaceutical Inc",
        "RARX" : "Ra Pharmaceuticals Inc",
        "RBA" : "Ritchie Bros. Auctioneers Inc",
        "RBC" : "Regal Beloit Corp",
        "RCL" : "Royal Caribbean Cruises Ltd",
        "RCM" : "R1 RCM Inc",
        "RDN" : "Radian Group Inc",
        "RE" : "Everest Re Group Ltd",
        "REGN" : "Regeneron Pharmaceuticals Inc",
        "RETA" : "Reata Pharmaceuticals Inc",
        "REXR" : "Rexford Industrial Realty Inc",
        "RF" : "Regions Financial Corp",
        "RGA" : "Reinsurance Group of America Inc",
        "RGEN" : "Repligen Corp",
        "RGLD" : "Royal Gold Inc",
        "RH" : "RH",
        "RHI" : "Robert Half International Inc",
        "RHP" : "Ryman Hospitality Properties Inc",
        "RIG" : "Transocean Ltd",
        "RJF" : "Raymond James Financial Inc",
        "RL" : "Ralph Lauren Corp",
        "RLI" : "RLI Corp",
        "RLJ" : "RLJ Lodging Trust",
        "RMD" : "ResMed Inc",
        "RNG" : "RingCentral Inc",
        "RNR" : "Renaissancere Holdings Ltd",
        "RNST" : "Renasant Corp",
        "ROG" : "Rogers Corp",
        "ROIC" : "Retail Opportunity Investments Corp",
        "ROK" : "Rockwell Automation Inc",
        "ROKU" : "Roku Inc",
        "ROL" : "Rollins Inc",
        "ROLL" : "RBC Bearings Inc",
        "ROP" : "Roper Technologies Inc",
        "ROST" : "Ross Stores Inc",
        "RP" : "RealPage Inc",
        "RPAI" : "Retail Properties of America Inc",
        "RPD" : "Rapid7 Inc",
        "RPM" : "RPM International Inc",
        "RS" : "Reliance Steel & Aluminum Co",
        "RSG" : "Republic Services Inc",
        "RTN" : "Raytheon Co",
        "RWT" : "Redwood Trust Inc",
        "RXN" : "Rexnord Corp",
        "S" : "Sprint Corp",
        "SABR" : "Sabre Corp",
        "SAFM" : "Sanderson Farms Inc",
        "SAGE" : "SAGE Therapeutics Inc",
        "SAIA" : "Saia Inc",
        "SAIC" : "Science Applications International Corp",
        "SAIL" : "SailPoint Technologies Holdings Inc",
        "SAM" : "Boston Beer Company Inc",
        "SANM" : "Sanmina Corp",
        "SATS" : "EchoStar Corp",
        "SAVE" : "Spirit Airlines Inc",
        "SBAC" : "SBA Communications Corp",
        "SBGI" : "Sinclair Broadcast Group Inc",
        "SBH" : "Sally Beauty Holdings Inc",
        "SBRA" : "Sabra Health Care REIT Inc",
        "SBUX" : "Starbucks Corp",
        "SC" : "Santander Consumer USA Holdings Inc",
        "SCCO" : "Southern Copper Corp",
        "SCEpB" : "Southern California Edison Co",
        "SCHW" : "Charles Schwab Corp",
        "SCI" : "Service Corporation International",
        "SCL" : "Stepan Co",
        "SCS" : "Steelcase Inc",
        "SEAS" : "SeaWorld Entertainment Inc",
        "SEB" : "Seaboard Corp",
        "SEDG" : "Solaredge Technologies Inc",
        "SEE" : "Sealed Air Corp",
        "SEIC" : "SEI Investments Co",
        "SEM" : "Select Medical Holdings Corp",
        "SERV" : "Servicemaster Global Holdings Inc",
        "SF" : "Stifel Financial Corp",
        "SFIX" : "Stitch Fix Inc",
        "SFM" : "Sprouts Farmers Market Inc",
        "SFNC" : "Simmons First National Corp",
        "SGEN" : "Seattle Genetics Inc",
        "SGMS" : "Scientific Games Corp",
        "SHAK" : "Shake Shack Inc",
        "SHLX" : "Shell Midstream Partners LP",
        "SHO" : "Sunstone Hotel Investors Inc",
        "SHOO" : "Steven Madden Ltd",
        "SHW" : "Sherwin-Williams Co",
        "SIGI" : "Selective Insurance Group Inc",
        "SIRI" : "Sirius XM Holdings Inc",
        "SITC" : "SITE Centers Corp",
        "SITE" : "SiteOne Landscape Supply Inc",
        "SIVB" : "SVB Financial Group",
        "SIX" : "Six Flags Entertainment Corp",
        "SJI" : "South Jersey Industries Inc",
        "SJM" : "J M Smucker Co",
        "SJW" : "SJW Group",
        "SKX" : "Skechers USA Inc",
        "SKYW" : "SkyWest Inc",
        "SLAB" : "Silicon Laboratories Inc",
        "SLG" : "SL Green Realty Corp",
        "SLGN" : "Silgan Holdings Inc",
        "SLM" : "SLM Corp",
        "SLNM" : "Salon Media Group Inc",
        "SMAR" : "Smartsheet Inc",
        "SMG" : "Scotts Miracle-Gro Co",
        "SMPL" : "Simply Good Foods Co",
        "SMTC" : "Semtech Corp",
        "SNA" : "Snap-On Inc",
        "SNAP" : "Snap Inc",
        "SNDR" : "Schneider National Inc",
        "SNPS" : "Synopsys Inc",
        "SNV" : "Synovus Financial Corp",
        "SNX" : "SYNNEX Corp",
        "SO" : "Southern Co",
        "SON" : "Sonoco Products Co",
        "SPAQ" : "Spartan Energy Acquisition Corp.",
        "SPB" : "Spectrum Brands Holdings Inc",
        "SPG" : "Simon Property Group Inc",
        "SPGI" : "S&P Global Inc",
        "SPGZ" : "Spectrum Group International Inc",
        "SPLK" : "Splunk Inc",
        "SPR" : "Spirit AeroSystems Holdings Inc",
        "SPSC" : "SPS Commerce Inc",
        "SPXC" : "SPX Corp",
        "SQ" : "Square Inc",
        "SR" : "Spire Inc",
        "SRC" : "Spirit Realty Capital Inc",
        "SRCL" : "Stericycle Inc",
        "SRE" : "Sempra Energy",
        "SRPT" : "Sarepta Therapeutics Inc",
        "SSB" : "South State Corp",
        "SSD" : "Simpson Manufacturing Co Inc",
        "SSNC" : "SS&C Technologies Holdings Inc",
        "ST" : "Sensata Technologies Holding NV",
        "STAG" : "STAG Industrial Inc",
        "STAY" : "Extended Stay America Inc",
        "STE" : "STERIS plc",
        "STI" : "SunTrust Banks Inc",
        "STL" : "Sterling Bancorp",
        "STLD" : "Steel Dynamics Inc",
        "STOR" : "Store Capital Corp",
        "STRA" : "Strayer Education Inc",
        "STT" : "State Street Corp",
        "STWD" : "Starwood Property Trust Inc",
        "STX" : "Seagate Technology PLC",
        "SUI" : "Sun Communities Inc",
        "SUN" : "Sunoco LP",
        "SVMK" : "SVMK Inc.",
        "SWI" : "SolarWinds Corp",
        "SWK" : "Stanley Black & Decker Inc",
        "SWKS" : "Skyworks Solutions Inc",
        "SWX" : "Southwest Gas Holdings Inc",
        "SXT" : "Sensient Technologies Corp",
        "SYF" : "Synchrony Financial",
        "SYK" : "Stryker Corp",
        "SYNH" : "Syneos Health Inc",
        "SYY" : "Sysco Corp",
        "T" : "AT&T Inc",
        "TAP" : "Molson Coors Brewing Co",
        "TCBI" : "Texas Capital Bancshares Inc",
        "TCO" : "Taubman Centers Inc",
        "TCP" : "TC PipeLines LP",
        "TDC" : "Teradata Corp",
        "TDG" : "TransDigm Group Inc",
        "TDOC" : "Teladoc Inc",
        "TDS" : "Telephone and Data Systems Inc",
        "TDY" : "Teledyne Technologies Inc",
        "TECD" : "Tech Data Corp",
        "TECH" : "Bio-Techne Corp",
        "TEL" : "TE Connectivity Ltd",
        "TENB" : "Tenable Holdings Inc",
        "TER" : "Teradyne Inc",
        "TERP" : "TerraForm Power Inc",
        "TEVA" : "Teva Pharmaceutical Industries Ltd",
        "TEX" : "Terex Corp",
        "TFSL" : "TFS Financial Corp",
        "TFX" : "Teleflex Inc",
        "TGE" : "Tallgrass Energy GP LP",
        "TGNA" : "Tegna Inc",
        "TGT" : "Target Corp",
        "THC" : "Tenet Healthcare Corp",
        "THG" : "Hanover Insurance Group Inc",
        "THO" : "Thor Industries Inc",
        "THS" : "TreeHouse Foods Inc",
        "TIF" : "Tiffany & Co",
        "TJX" : "TJX Companies Inc",
        "TKR" : "Timken Co",
        "TMO" : "Thermo Fisher Scientific Inc",
        "TMUS" : "T-Mobile US Inc",
        "TNDM" : "Tandem Diabetes Care Inc",
        "TNET" : "TriNet Group Inc",
        "TOL" : "Toll Brothers Inc",
        "TPH" : "TRI Pointe Group Inc",
        "TPL" : "Texas Pacific Land Trust",
        "TPR" : "Tapestry Inc",
        "TPX" : "Tempur Sealy International Inc",
        "TR" : "Tootsie Roll Industries Inc",
        "TREE" : "LendingTree Inc",
        "TREX" : "Trex Company Inc",
        "TRGP" : "Targa Resources Corp",
        "TRIP" : "TripAdvisor Inc",
        "TRMB" : "Trimble Inc",
        "TRMK" : "Trustmark Corp",
        "TRN" : "Trinity Industries Inc",
        "TRNO" : "Terreno Realty Corp",
        "TROW" : "T. Rowe Price Group Inc",
        "TRTN" : "Triton International Ltd",
        "TRU" : "TransUnion",
        "TRV" : "Travelers Companies Inc",
        "TSCO" : "Tractor Supply Co",
        "TSLA" : "Tesla Inc",
        "TSN" : "Tyson Foods Inc",
        "TTC" : "Toro Co",
        "TTD" : "Trade Desk Inc",
        "TTEC" : "TTEC Holdings Inc",
        "TTEK" : "Tetra Tech Inc",
        "TTWO" : "Take-Two Interactive Software Inc",
        "TWLO" : "Twilio Inc",
        "TWO" : "Two Harbors Investment Corp",
        "TWTR" : "Twitter Inc",
        "TXN" : "Texas Instruments Inc",
        "TXRH" : "Texas Roadhouse Inc",
        "TXT" : "Textron Inc",
        "TYL" : "Tyler Technologies Inc",
        "UA" : "Under Armour Inc",
        "UAL" : "United Continental Holdings Inc",
        "UBER" : "Uber Technologies Inc",
        "UBSI" : "United Bankshares Inc",
        "UCBI" : "United Community Banks Inc",
        "UDR" : "UDR Inc",
        "UE" : "Urban Edge Properties",
        "UFPI" : "Universal Forest Products Inc",
        "UFS" : "Domtar Corp",
        "UGI" : "UGI Corp",
        "UHAL" : "Amerco",
        "UHS" : "Universal Health Services Inc",
        "ULTA" : "Ulta Beauty Inc",
        "UMBF" : "UMB Financial Corp",
        "UMPQ" : "Umpqua Holdings Corp",
        "UNF" : "UniFirst Corp",
        "UNH" : "UnitedHealth Group Inc",
        "UNM" : "Unum Group",
        "UNP" : "Union Pacific Corp",
        "UNVR" : "Univar Inc",
        "UPS" : "United Parcel Service Inc",
        "URBN" : "Urban Outfitters Inc",
        "URI" : "United Rentals Inc",
        "USB" : "U.S. Bancorp",
        "USFD" : "US Foods Holding Corp",
        "USM" : "United States Cellular Corp",
        "UTHR" : "United Therapeutics Corp",
        "UTX" : "United Technologies Corp",
        "VAC" : "Marriott Vacations Worldwide Corp",
        "VAR" : "Varian Medical Systems Inc",
        "VC" : "Visteon Corp",
        "VEEV" : "Veeva Systems Inc",
        "VER" : "Vereit Inc",
        "VFC" : "VF Corp",
        "VGR" : "Vector Group Ltd",
        "VIA" : "Viacom Inc",
        "VIAV" : "Viavi Solutions Inc",
        "VICI" : "VICI Properties Inc",
        "VLO" : "Valero Energy Corp",
        "VLY" : "Valley National Bancorp",
        "VMC" : "Vulcan Materials Co",
        "VMI" : "Valmont Industries Inc",
        "VMW" : "VMware Inc",
        "VNO" : "Vornado Realty Trust",
        "VOYA" : "Voya Financial Inc",
        "VRNS" : "Varonis Systems Inc",
        "VRNT" : "Verint Systems Inc",
        "VRSK" : "Verisk Analytics Inc",
        "VRSN" : "Verisign Inc",
        "VRTX" : "Vertex Pharmaceuticals Inc",
        "VSAT" : "ViaSat Inc",
        "VST" : "Vistra Energy Corp",
        "VTR" : "Ventas Inc",
        "VVV" : "Valvoline Inc",
        "VZ" : "Verizon Communications Inc",
        "W" : "Wayfair Inc",
        "WAB" : "Westinghouse Air Brake Technologies Corp",
        "WAFD" : "Washington Federal Inc",
        "WAL" : "Western Alliance Bancorp",
        "WAT" : "Waters Corp",
        "WBA" : "Walgreens Boots Alliance Inc",
        "WBC" : "WABCO Holdings Inc",
        "WBS" : "Webster Financial Corp",
        "WBT" : "Welbilt Inc",
        "WCC" : "Wesco International Inc",
        "WCG" : "WellCare Health Plans Inc",
        "WCN" : "Waste Connections Inc",
        "WD" : "Walker & Dunlop Inc",
        "WDAY" : "Workday Inc",
        "WDC" : "Western Digital Corp",
        "WDFC" : "WD-40 Co",
        "WEC" : "WEC Energy Group Inc",
        "WELL" : "Welltower Inc",
        "WEN" : "Wendys Co",
        "WERN" : "Werner Enterprises Inc",
        "WES" : "Western Midstream Operating, LP",
        "WEX" : "WEX Inc",
        "WFC" : "Wells Fargo & Co",
        "WH" : "Wyndham Hotels & Resorts Inc",
        "WHR" : "Whirlpool Corp",
        "WING" : "Wingstop Inc",
        "WK" : "Workiva Inc",
        "WLK" : "Westlake Chemical Corp",
        "WLKP" : "Westlake Chemical Partners LP",
        "WLTW" : "Willis Towers Watson PLC",
        "WM" : "Waste Management Inc",
        "WMB" : "Williams Companies Inc",
        "WMGI" : "Wright Medical Group NV",
        "WMS" : "Advanced Drainage Systems Inc",
        "WMT" : "Walmart Inc",
        "WOR" : "Worthington Industries Inc",
        "WPC" : "WP Carey Inc",
        "WPX" : "WPX Energy Inc",
        "WRB" : "W. R. Berkley Corp",
        "WRE" : "Washington Real Estate Investment Trust",
        "WRI" : "Weingarten Realty Investors",
        "WRK" : "Westrock Co",
        "WSFS" : "WSFS Financial Corp",
        "WSM" : "Williams-Sonoma Inc",
        "WSO" : "Watsco Inc",
        "WST" : "West Pharmaceutical Services Inc",
        "WTFC" : "Wintrust Financial Corp",
        "WTM" : "White Mountains Insurance Group Ltd",
        "WTR" : "Aqua America Inc",
        "WTS" : "Watts Water Technologies Inc",
        "WU" : "Western Union Co",
        "WW" : "Weight Watchers International Inc",
        "WWD" : "Woodward Inc",
        "WWE" : "World Wrestling Entertainment Inc",
        "WWW" : "Wolverine World Wide Inc",
        "WY" : "Weyerhaeuser Co",
        "WYND" : "Wyndham Worldwide Corp",
        "WYNN" : "Wynn Resorts Ltd",
        "X" : "United States Steel Corp",
        "XEC" : "Cimarex Energy Co",
        "XEL" : "Xcel Energy Inc",
        "XHR" : "Xenia Hotels & Resorts Inc",
        "XLNX" : "Xilinx Inc",
        "XLRN" : "Acceleron Pharma Inc",
        "XNCR" : "Xencor Inc",
        "XOM" : "Exxon Mobil Corp",
        "XPO" : "XPO Logistics Inc",
        "XRAY" : "Dentsply Sirona Inc",
        "XRX" : "Xerox Corp",
        "XYL" : "Xylem Inc",
        "Y" : "Alleghany Corp",
        "YELP" : "Yelp Inc",
        "YETI" : "Yeti Holdings Inc",
        "YUM" : "Yum! Brands Inc",
        "Z" : "Zillow Group Inc",
        "ZAYO" : "Zayo Group Holdings Inc",
        "ZBH" : "Zimmer Biomet Holdings Inc",
        "ZBRA" : "Zebra Technologies Corp",
        "ZEN" : "Zendesk Inc",
        "ZGNX" : "Zogenix Inc",
        "ZION" : "Zions Bancorp",
        "ZM" : "Zoom Video Communications Inc",
        "ZNGA" : "Zynga Inc",
        "ZTS" : "Zoetis Inc"
    ]
}
